function res = ARK_order_conditions(BE, BI, maxorder)
    % Usage: res = ARK_order_conditions(BE, BI, maxorder)
    %
    %        Inputs:
    %          BE is the explicit Butcher table, with components:
    %             BE.A -- the Butcher table matrix
    %             BE.b -- the solution coefficients
    %          BI is the implicit Butcher table, with the same components
    %          maxorder is optional, specifying the highest order of
    %             conditions to generate (default 4)
    %
    %        Outputs:
    %          res is a cell array indexed by order q = 1,...,maxorder, where
    %             res{q} is a containers.Map mapping a label for each order-q
    %             condition to its residual (zero when the condition holds)
    %
    %        The abscissae for each table are computed as c = A*1 (internal
    %        consistency), so that the tables need not share their abscissae.
    %        The conditions and their labels are those of ARK_conditions, where
    %        '.' denotes a matrix product and C = diag(c), e.g., 'bE.AI.cE'
    %        denotes (bE)^T AI cE - 1/6, and 'bI.CE.cI' denotes
    %        (bI)^T diag(cE) cI - 1/3.  Labels where all factors use the same
    %        table are the order conditions for that table alone; all others
    %        are coupling conditions.  Inputs may be double arrays, or sym
    %        arrays with exact (rational or symbolic) entries.
    %
% Function to check the order conditions (including the coupling conditions)
% for two-component additive Runge--Kutta (ARK) methods.  The order conditions
% are generated by ARK_conditions, so they may be checked to any order.
%
% Daniel R. Reynolds
% Math & Stat @ UMBC
%
if nargin < 3 || isempty(maxorder)
    maxorder = 4;
end

% set up tables and abscissae
A.E = sym(BE.A);  A.I = sym(BI.A);
b.E = sym(BE.b(:));  b.I = sym(BI.b(:));
s = size(A.E, 1);
if ((size(A.I, 1) ~= s) || (size(b.E, 1) ~= s) || (size(b.I, 1) ~= s))
    error('ARK_order_conditions ERROR: incompatible Butcher tables supplied');
end
one = sym(ones(s, 1));
c.E = A.E*one;  c.I = A.I*one;

% generate conditions, each of the form (b^u)^T v = rhs
res = cell(1, maxorder);
for q = 1:maxorder
    res{q} = containers.Map('KeyType', 'char', 'ValueType', 'any');
    conds = ARK_conditions(q);
    for k = 1:numel(conds)
        label = conds(k).label;
        res{q}(label) = dot(b.(label(2)), vector(label(4:end))) - conds(k).rhs;
    end
end

% simplify residuals
for q = 1:maxorder
    labels = keys(res{q});
    for k = 1:numel(labels)
        res{q}(labels{k}) = simplify(res{q}(labels{k}));
    end
end

    function d = dot(u, v)
        d = sym(0);
        for i = 1:s
            d = d + u(i)*v(i);
        end
    end

    function h = hadamard(u, v)
        h = sym(zeros(s, 1));
        for i = 1:s
            h(i) = u(i)*v(i);
        end
    end

    function factors = split_label(label)
        % split a label into its factors, at the '.' outside of any parentheses
        factors = {};
        depth = 0;
        start = 1;
        for i = 1:numel(label)
            if (label(i) == '(')
                depth = depth + 1;
            elseif (label(i) == ')')
                depth = depth - 1;
            elseif ((label(i) == '.') && (depth == 0))
                factors{end+1} = label(start:i-1);
                start = i+1;
            end
        end
        factors{end+1} = label(start:end);
    end

    function v = vector(label)
        % evaluate a label for a vector: a product of matrix factors (A, C or
        % diag(...)) ending in the vector c or 1
        factors = split_label(label);
        if strcmp(factors{end}, '1')
            v = one;
        else
            v = c.(factors{end}(2));
        end
        for j = numel(factors)-1:-1:1
            f = factors{j};
            if startsWith(f, 'diag(')
                v = hadamard(vector(f(6:end-1)), v);
            elseif (f(1) == 'C')
                v = hadamard(c.(f(2)), v);
            else
                v = A.(f(2))*v;
            end
        end
    end
end
