#!/usr/bin/env python
# Functions to check the order conditions (including the coupling conditions)
# for generalized-structure additive Runge--Kutta (GARK) methods with M
# partitions.  The order conditions are generated by enumerating rooted trees
# whose vertices are colored by the partitions 1,...,M, so they may be checked
# to any order.  Also includes a function to construct the GARK tableau of a
# fractional-step Runge--Kutta (FSRK) method, and a simple "main" that uses
# these functions to examine an ARK method written in GARK form, and several
# fractional-step methods from the lecture notes.
#
# Each vertex of a tree carries a color.  The root, of color sigma,
# contributes the solution weights b^{sigma}; a vertex of color nu attached to
# a parent of color mu contributes A^{mu,nu}; and so a leaf of color nu
# attached to a parent of color mu contributes c^{mu,nu} = A^{mu,nu}*1.
#
# In condition labels, '.' denotes a matrix product, e.g., 'b{1}.A{1,2}.c{2,1}'
# denotes (b^{1})^T A^{1,2} c^{2,1}.  A componentwise product with a vector is
# written as a product with the corresponding diagonal matrix, C = diag(c),
# e.g., 'b{1}.C{1,2}.c{1,1}' denotes (b^{1})^T diag(c^{1,2}) c^{1,1}, and
# 'b{1}.diag(A{1,2}.c{2,1}).A{1,1}.c{1,2}' denotes
# (b^{1})^T diag(A^{1,2} c^{2,1}) A^{1,1} c^{1,2}.
#
# Daniel R. Reynolds
# Math & Stat @ UMBC

# general imports
import numpy as np
import os
import sympy as sp
import sys
from functools import lru_cache
from itertools import combinations_with_replacement
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))
from utilities.rooted_trees import partitions

@lru_cache(None)
def colored_trees(n, M):
    ''' Usage: trees = colored_trees(n, M)

        Returns a frozenset of the distinct rooted trees with n vertices,
        with each vertex colored by one of the partitions 1,...,M.  Each tree
        is stored as a tuple (color, children), where children is a sorted
        tuple of subtrees.
    '''
    trees = set()
    for part in partitions(n-1):
        # count the number of children of each size
        sizes = {}
        for k in part:
            sizes[k] = sizes.get(k, 0) + 1
        # form every multiset of subtrees having these sizes
        childlists = [()]
        for k, m in sizes.items():
            subtrees = sorted(colored_trees(k, M))
            childlists = [a + b for a in childlists
                          for b in combinations_with_replacement(subtrees, m)]
        # color the root of each resulting tree
        for children in childlists:
            children = tuple(sorted(children))
            for color in range(1, M+1):
                trees.add((color, children))
    return frozenset(trees)


def tree_order(t):
    ''' Usage: n = tree_order(t)

        Returns the number of vertices in the tree t.
    '''
    return 1 + sum(tree_order(child) for child in t[1])


def tree_density(t):
    ''' Usage: gamma = tree_density(t)

        Returns the density gamma(t) of the tree t, so that the order
        condition for t is Phi(t) = 1/gamma(t).
    '''
    gamma = tree_order(t)
    for child in t[1]:
        gamma *= tree_density(child)
    return gamma


def tree_colors(t):
    ''' Usage: colors = tree_colors(t)

        Returns the set of colors used in the tree t.
    '''
    colors = {t[0]}
    for child in t[1]:
        colors |= tree_colors(child)
    return colors


def vector_label(color, children):
    ''' Usage: label = vector_label(color, children)

        Returns the label for the vector formed by the elementwise product of
        the terms contributed by each child subtree of a vertex with the given
        color.  Leaves contribute c (listed first), and all other subtrees
        contribute A times the vector for their own children.  Every term but
        the last multiplies the terms to its right elementwise, and so is
        written as a diagonal matrix, C = diag(c) or diag(A...).
    '''
    leaves = [t[0] for t in children if (len(t[1]) == 0)]
    terms = ['A{%i,%i}.' % (color, t[0]) + vector_label(t[0], t[1])
             for t in children if (len(t[1]) > 0)]
    factors = ['C{%i,%i}' % (color, x) for x in leaves] + ['diag(' + term + ')' for term in terms]
    factors[-1] = terms[-1] if (len(terms) > 0) else 'c{%i,%i}' % (color, leaves[-1])
    return '.'.join(factors)


def tree_label(t):
    ''' Usage: label = tree_label(t)

        Returns the label for the order condition corresponding to the full
        tree t.
    '''
    if (len(t[1]) == 0):
        return 'b{%i}.1' % (t[0])
    return 'b{%i}.' % (t[0]) + vector_label(t[0], t[1])


def GARK_order_conditions(A, b, maxorder=4):
    ''' Usage: res = GARK_order_conditions(A, b, maxorder)

        Inputs:
          A is a list of M lists, where A[sigma][nu] is the GARK coefficient
             block A^{sigma+1,nu+1}, of size s^{sigma+1} x s^{nu+1}
          b is a list of M vectors, where b[sigma] holds the solution
             weights b^{sigma+1}, of length s^{sigma+1}
          maxorder is optional, specifying the highest order of
             conditions to generate (default 4)

        Outputs:
          res is a dictionary indexed by order q = 1,...,maxorder, where
             res[q] is itself a dictionary mapping a label for each order-q
             condition to its residual (zero when the condition holds)

        Partitions are numbered 1,...,M in the condition labels, and the
        vectors c^{sigma,nu} = A^{sigma,nu}*1 are computed from the blocks,
        so that the method need not be internally consistent.  Labels where
        all factors use the same partition are the order conditions for that
        partition's base method; all others are coupling conditions.  Inputs
        may be numpy arrays of floats, or sympy matrices with exact
        (rational or symbolic) entries.
    '''

    # set up tables
    M = len(b)
    A = [[sp.Matrix(A[i][j]) for j in range(M)] for i in range(M)]
    b = [sp.Matrix(b[i]) for i in range(M)]
    s = [b[i].shape[0] for i in range(M)]
    for i in range(M):
        for j in range(M):
            if (A[i][j].shape != (s[i], s[j])):
                raise ValueError("GARK_order_conditions ERROR: incompatible GARK blocks supplied")
    def dot(u,v):
        return sum(u[i]*v[i] for i in range(len(u)))
    def hadamard(u,v):
        return sp.Matrix([u[i]*v[i] for i in range(len(u))])
    def vector(color, children):
        # elementwise product, over the children, of A^{color,child} times the
        # vector for each child's own children (a leaf gives A^{color,child}*1)
        v = sp.ones(s[color-1],1)
        for child in children:
            v = hadamard(v, A[color-1][child[0]-1]*vector(child[0], child[1]))
        return v

    # generate conditions, sorted by right-hand side and then by label
    res = {q: {} for q in range(1,maxorder+1)}
    for q in range(1,maxorder+1):
        trees = sorted(colored_trees(q, M), key=lambda t: (-tree_density(t), tree_label(t)))
        for t in trees:
            res[q][tree_label(t)] = dot(b[t[0]-1], vector(t[0], t[1])) - sp.Rational(1, tree_density(t))

    # simplify residuals
    for q in res:
        for key in res[q]:
            res[q][key] = sp.simplify(res[q][key])
    return res


def GARK_order(A, b, tol=1e-10, maxorder=4, verbose=False):
    ''' Usage: p, failed = GARK_order(A, b, tol, maxorder, verbose)

        Inputs:
          A, b are the GARK coefficient blocks and solution weights (see
             GARK_order_conditions)
          tol is optional, specifying the tolerance for considering a
             residual to be zero (default 1e-10)
          maxorder is optional, specifying the highest order to check
             (default 4)
          verbose is optional, printing the failing conditions if True

        Outputs:
          p is the order of the GARK method (or maxorder, if all checked
             conditions hold)
          failed is a sorted list of the labels of the lowest-order failing
             conditions (empty if p == maxorder)
    '''
    res = GARK_order_conditions(A, b, maxorder)
    p = 0
    for q in range(1,maxorder+1):
        failed = sorted(key for key, val in res[q].items() if abs(complex(sp.N(val))) > tol)
        if (len(failed) > 0):
            if (verbose):
                print("  failing order-%i conditions:" % (q), failed)
            return p, failed
        p = q
    return p, []


def FSRK_tableau(alpha, B):
    ''' Usage: A, b = FSRK_tableau(alpha, B)

        Inputs:
          alpha is a list of M lists, where alpha[l] holds the fractions
             alpha_k^{l+1}, k=1,...,s, of the step taken by partition l+1 in
             each stage of the fractional-step method
          B is a list of M Butcher tables, where B[l] is the sub-integrator
             used for every sub-step of partition l+1, with components:
             B[l]['A'] -- the Butcher table matrix
             B[l]['b'] -- the solution coefficients

        Outputs:
          A, b are the GARK coefficient blocks and solution weights of the
             resulting fractional-step Runge--Kutta method (see
             GARK_order_conditions)

        The sub-steps are applied in the order (1,1),(1,2),...,(1,M),(2,1),
        ...,(s,M), i.e., within each stage partition 1 is advanced first.
    '''
    M = len(alpha)
    s = len(alpha[0])
    Bt = [{'A': sp.Matrix(B[l]['A']), 'b': sp.Matrix(B[l]['b'])} for l in range(M)]
    st = [Bt[l]['A'].shape[0] for l in range(M)]
    order = [(k,l) for k in range(s) for l in range(M)]
    A = [[sp.zeros(s*st[l], s*st[lp]) for lp in range(M)] for l in range(M)]
    for (k,l) in order:
        for (kp,lp) in order:
            if (order.index((kp,lp)) < order.index((k,l))):
                block = alpha[lp][kp]*sp.ones(st[l],1)*Bt[lp]['b'].T
            elif ((kp,lp) == (k,l)):
                block = alpha[l][k]*Bt[l]['A']
            else:
                continue
            A[l][lp][k*st[l]:(k+1)*st[l], kp*st[lp]:(kp+1)*st[lp]] = block
    b = [sp.Matrix.vstack(*[alpha[l][k]*Bt[l]['b'] for k in range(s)]) for l in range(M)]
    return A, b


# main routine
if __name__ == '__main__':

    R = sp.Rational

    # ARS (2,2,2), written in GARK form with A^{sigma,nu} = A^{nu}
    g = (2 - sp.sqrt(2))/2
    d = 1 - 1/(2*g)
    AE = sp.Matrix([[0, 0, 0], [g, 0, 0], [d, 1-d, 0]])
    AI = sp.Matrix([[0, 0, 0], [0, g, 0], [0, 1-g, g]])
    ARS222 = ([[AE, AI], [AE, AI]], [sp.Matrix([d, 1-d, 0]), sp.Matrix([0, 1-g, g])])

    # sub-integrators for the fractional-step methods
    FE = {'A': sp.Matrix([[0]]), 'b': sp.Matrix([1])}
    Heun = {'A': sp.Matrix([[0, 0], [1, 0]]), 'b': sp.Matrix([R(1,2), R(1,2)])}
    RK4 = {'A': sp.Matrix([[0, 0, 0, 0], [R(1,2), 0, 0, 0], [0, R(1,2), 0, 0], [0, 0, 1, 0]]),
           'b': sp.Matrix([R(1,6), R(1,3), R(1,3), R(1,6)])}

    # fractional-step coefficients from the catalogue in FractionalStep.py;
    # these are stored in floating point, so we recover their exact rational
    # values with nsimplify, to keep all arithmetic here exact
    import FractionalStep as fs
    def exact(S):
        return [[sp.nsimplify(a) for a in row] for row in S['alpha']]
    LT = exact(fs.LieTrotter())
    Strang = exact(fs.StrangMarchuk())
    Ruth = exact(fs.Ruth())
    def OS2(mu):
        return exact(fs.OS2(mu))

    tests = [('ARS(2,2,2) in GARK form', ARS222),
             ('Lie-Trotter + forward Euler', FSRK_tableau(LT, [FE, FE])),
             ('Lie-Trotter + RK4', FSRK_tableau(LT, [RK4, RK4])),
             ('Strang + RK4', FSRK_tableau(Strang, [RK4, RK4])),
             ('OS2(2,2)-1/4 + RK4', FSRK_tableau(OS2(0.25), [RK4, RK4])),
             ('OS2(2,2)-1/2 + RK4', FSRK_tableau(OS2(0.5), [RK4, RK4])),
             ('OS2(2,2)-2 + RK4', FSRK_tableau(OS2(2.0), [RK4, RK4])),
             ('Ruth + RK4', FSRK_tableau(Ruth, [RK4, RK4])),
             ('Ruth + Heun', FSRK_tableau(Ruth, [Heun, Heun]))]
    for name, (A, b) in tests:
        print("\n", name, ":", sep='')
        M = len(b)
        pbase = [GARK_order([[A[i][i]]], [b[i]], tol=1e-8)[0] for i in range(M)]
        p, failed = GARK_order(A, b, tol=1e-8)
        print("  base method orders = %s,  GARK order = %i" % (', '.join(str(q) for q in pbase), p))
        if (p < min(pbase)):
            print("  failing coupling conditions: %s" % (', '.join(failed)))
