function res = GARK_order_conditions(A, b, maxorder)
    % Usage: res = GARK_order_conditions(A, b, maxorder)
    %
    %        Inputs:
    %          A is an M-by-M cell array, where A{sigma,nu} is the GARK
    %             coefficient block A^{sigma,nu}, of size s^{sigma} x s^{nu}
    %          b is a cell array of M vectors, where b{sigma} holds the
    %             solution weights b^{sigma}, of length s^{sigma}
    %          maxorder is optional, specifying the highest order of
    %             conditions to generate (default 4)
    %
    %        Outputs:
    %          res is a cell array indexed by order q = 1,...,maxorder, where
    %             res{q} is a containers.Map mapping a label for each order-q
    %             condition to its residual (zero when the condition holds)
    %
    %        Partitions are numbered 1,...,M in the condition labels, and the
    %        vectors c^{sigma,nu} = A^{sigma,nu}*1 are computed from the blocks,
    %        so that the method need not be internally consistent.  Labels
    %        where all factors use the same partition are the order conditions
    %        for that partition's base method; all others are coupling
    %        conditions.  Inputs may be double arrays, or sym arrays with exact
    %        (rational or symbolic) entries.
    %
% Function to check the order conditions (including the coupling conditions)
% for generalized-structure additive Runge--Kutta (GARK) methods with M
% partitions.  The order conditions are generated by enumerating rooted trees
% whose vertices are colored by the partitions 1,...,M (at most 9), so they
% may be checked to any order.
%
% Each vertex of a tree carries a color.  The root, of color sigma,
% contributes the solution weights b^{sigma}; a vertex of color nu attached to
% a parent of color mu contributes A^{mu,nu}; and so a leaf of color nu
% attached to a parent of color mu contributes c^{mu,nu} = A^{mu,nu}*1.
%
% In condition labels, '.' denotes a matrix product, e.g., 'b{1}.A{1,2}.c{2,1}'
% denotes (b^{1})^T A^{1,2} c^{2,1}.  A componentwise product with a vector is
% written as a product with the corresponding diagonal matrix, C = diag(c),
% e.g., 'b{1}.C{1,2}.c{1,1}' denotes (b^{1})^T diag(c^{1,2}) c^{1,1}, and
% 'b{1}.diag(A{1,2}.c{2,1}).A{1,1}.c{1,2}' denotes
% (b^{1})^T diag(A^{1,2} c^{2,1}) A^{1,1} c^{1,2}.
%
% Daniel R. Reynolds
% Math & Stat @ UMBC
%
if nargin < 3 || isempty(maxorder)
    maxorder = 4;
end

% partitions is in the utilities folder
addpath(fullfile(fileparts(fileparts(mfilename('fullpath'))), 'utilities'));

% set up tables
M = numel(b);
Asym = cell(M, M);
bsym = cell(1, M);
s = zeros(1, M);
for i = 1:M
    bsym{i} = sym(b{i}(:));
    s(i) = numel(bsym{i});
end
for i = 1:M
    for j = 1:M
        Asym{i,j} = sym(A{i,j});
        if (any(size(Asym{i,j}) ~= [s(i), s(j)]))
            error('GARK_order_conditions ERROR: incompatible GARK blocks supplied');
        end
    end
end

% generate conditions
res = cell(1, maxorder);
for q = 1:maxorder
    res{q} = containers.Map('KeyType', 'char', 'ValueType', 'any');
    trees = colored_trees(q, M);
    for k = 1:numel(trees)
        [color, children] = tree_parts(trees{k});
        res{q}(tree_label(trees{k})) = dot(bsym{color}, vector(color, children)) - sym(1)/tree_density(trees{k});
    end
end

% simplify residuals
for q = 1:maxorder
    labels = keys(res{q});
    for k = 1:numel(labels)
        res{q}(labels{k}) = simplify(res{q}(labels{k}));
    end
end

    function d = dot(u, v)
        d = sym(0);
        for i1 = 1:numel(u)
            d = d + u(i1)*v(i1);
        end
    end

    function v = vector(vcolor, vchildren)
        % elementwise product, over the children, of A^{vcolor,child} times
        % the vector for each child's own children (a leaf gives
        % A^{vcolor,child}*1)
        v = sym(ones(s(vcolor), 1));
        for j1 = 1:numel(vchildren)
            [ccolor, cchildren] = tree_parts(vchildren{j1});
            w = Asym{vcolor, ccolor}*vector(ccolor, cchildren);
            for i1 = 1:numel(v)
                v(i1) = v(i1)*w(i1);
            end
        end
    end
end


function combos = combinations_with_replacement(items, m)
    % Usage: combos = combinations_with_replacement(items, m)
    %
    %        Returns a cell array of every multiset of m entries from the cell
    %        array items, each as a 1-by-m cell array.
    %
if (m == 0)
    combos = {{}};
    return
end
combos = {};
for i = 1:numel(items)
    rest = combinations_with_replacement(items(i:end), m-1);
    for j = 1:numel(rest)
        combos{end+1} = [items(i), rest{j}];
    end
end
end


function trees = colored_trees(n, M)
    % Usage: trees = colored_trees(n, M)
    %
    %        Returns a sorted cell array of the distinct rooted trees with n
    %        vertices, with each vertex colored by one of the partitions
    %        1,...,M.  Each tree is stored as a character string
    %        [color '(' children ')'], where color is the partition number and
    %        children is the concatenation of the sorted strings for its
    %        subtrees.
    %
persistent cache
if isempty(cache)
    cache = containers.Map('KeyType', 'char', 'ValueType', 'any');
end
key = sprintf('%i,%i', n, M);
if isKey(cache, key)
    trees = cache(key);
    return
end

trees = {};
parts = partitions(n-1);
for p = 1:numel(parts)
    part = parts{p};
    % count the number of children of each size
    sizes = reshape(unique(part), 1, []);
    % form every multiset of subtrees having these sizes
    childlists = {{}};
    for k = sizes
        m = sum(part == k);
        combos = combinations_with_replacement(colored_trees(k, M), m);
        newlists = {};
        for a = 1:numel(childlists)
            for b = 1:numel(combos)
                newlists{end+1} = [childlists{a}, combos{b}];
            end
        end
        childlists = newlists;
    end
    % color the root of each resulting tree
    for j = 1:numel(childlists)
        children = sort(childlists{j});
        for color = 1:M
            trees{end+1} = [sprintf('%i', color), '(', children{:}, ')'];
        end
    end
end
trees = unique(trees);
cache(key) = trees;
end


function [color, children] = tree_parts(t)
    % Usage: [color, children] = tree_parts(t)
    %
    %        Returns the root color and the cell array of subtree strings for
    %        the tree string t.
    %
color = t(1) - '0';
children = {};
i = 3;
while (i < numel(t))
    start = i;
    depth = 0;
    i = i + 1;
    while true
        if (t(i) == '(')
            depth = depth + 1;
        elseif (t(i) == ')')
            depth = depth - 1;
        end
        if (depth == 0)
            break
        end
        i = i + 1;
    end
    children{end+1} = t(start:i);
    i = i + 1;
end
end


function n = tree_order(t)
    % Usage: n = tree_order(t)
    %
    %        Returns the number of vertices in the tree t.
    %
[~, children] = tree_parts(t);
n = 1;
for k = 1:numel(children)
    n = n + tree_order(children{k});
end
end


function gamma = tree_density(t)
    % Usage: gamma = tree_density(t)
    %
    %        Returns the density gamma(t) of the tree t, so that the order
    %        condition for t is Phi(t) = 1/gamma(t).
    %
[~, children] = tree_parts(t);
gamma = tree_order(t);
for k = 1:numel(children)
    gamma = gamma * tree_density(children{k});
end
end


function label = vector_label(color, children)
    % Usage: label = vector_label(color, children)
    %
    %        Returns the label for the vector formed by the elementwise product
    %        of the terms contributed by each child subtree of a vertex with
    %        the given color.  Leaves contribute c (listed first), and all other
    %        subtrees contribute A times the vector for their own children.
    %        Every term but the last multiplies the terms to its right
    %        elementwise, and so is written as a diagonal matrix, C = diag(c) or
    %        diag(A...).
    %
leaves = [];
terms = {};
for k = 1:numel(children)
    [ccolor, grandchildren] = tree_parts(children{k});
    if isempty(grandchildren)
        leaves(end+1) = ccolor;
    else
        terms{end+1} = [sprintf('A{%i,%i}.', color, ccolor), vector_label(ccolor, grandchildren)];
    end
end
factors = {};
for k = 1:numel(leaves)
    factors{end+1} = sprintf('C{%i,%i}', color, leaves(k));
end
for k = 1:numel(terms)
    factors{end+1} = ['diag(', terms{k}, ')'];
end
if ~isempty(terms)
    factors{end} = terms{end};
else
    factors{end} = sprintf('c{%i,%i}', color, leaves(end));
end
label = strjoin(factors, '.');
end


function label = tree_label(t)
    % Usage: label = tree_label(t)
    %
    %        Returns the label for the order condition corresponding to the
    %        full tree t.
    %
[color, children] = tree_parts(t);
if isempty(children)
    label = sprintf('b{%i}.1', color);
    return
end
label = [sprintf('b{%i}.', color), vector_label(color, children)];
end
